# Generated by Django 4.0.4 on 2022-05-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_alter_place_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
